/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebacomponentes.appexecutionplanner;

/**
 *
 * @author Bailon
 */
public class PruebaAppExecutionPlanner extends javax.swing.JFrame {

    /**
     * Creates new form PruebaAppExecutionPlanner
     */
    public PruebaAppExecutionPlanner() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appExecutionPlanner1 = new componentes.appexecutionplanner.AppExecutionPlanner();
        appExecutionPlanner2 = new componentes.appexecutionplanner.AppExecutionPlanner();
        appExecutionPlanner3 = new componentes.appexecutionplanner.AppExecutionPlanner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        appExecutionPlanner1.setAplicacionEjecutable(new componentes.appexecutionplanner.AplicacionEjecutable("C:\\Windows\\write.exe"));
        appExecutionPlanner1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        appExecutionPlanner1.setFechaHoraDigital(new componentes.appexecutionplanner.FechaHoraDigital(false,true));
        appExecutionPlanner1.setFechaPlanificada(new componentes.appexecutionplanner.FechaPlanificada(new java.util.Date().getTime(),17,10,20));

        appExecutionPlanner2.setAplicacionEjecutable(new componentes.appexecutionplanner.AplicacionEjecutable("C:\\Windows\\notepad.exe"));
        appExecutionPlanner2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        appExecutionPlanner2.setFechaHoraDigital(new componentes.appexecutionplanner.FechaHoraDigital(true,true));
        appExecutionPlanner2.setFechaPlanificada(new componentes.appexecutionplanner.FechaPlanificada(new java.util.Date().getTime(),17,30,0));

        appExecutionPlanner3.setAplicacionEjecutable(new componentes.appexecutionplanner.AplicacionEjecutable("C:\\Windows\\winhlp32.exe"));
        appExecutionPlanner3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        appExecutionPlanner3.setFechaPlanificada(new componentes.appexecutionplanner.FechaPlanificada(new java.util.Date().getTime(),17,40,5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appExecutionPlanner1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
            .addComponent(appExecutionPlanner2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(appExecutionPlanner3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(appExecutionPlanner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(appExecutionPlanner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(appExecutionPlanner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaAppExecutionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaAppExecutionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaAppExecutionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaAppExecutionPlanner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaAppExecutionPlanner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.appexecutionplanner.AppExecutionPlanner appExecutionPlanner1;
    private componentes.appexecutionplanner.AppExecutionPlanner appExecutionPlanner2;
    private componentes.appexecutionplanner.AppExecutionPlanner appExecutionPlanner3;
    // End of variables declaration//GEN-END:variables
}
