/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package componentes.appexecutionplanner;

import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;



/**
 * Panel de edicion de la propiedad AplicacionEjecutable
 * @author Jose Javier BO
 */
public class AplicacionEjecutablelPanel extends javax.swing.JPanel {
    
    AplicacionEjecutable aej=new AplicacionEjecutable("");
    
    /**
     * Creates new form FechaHoraDigitalPanel
     */
    public AplicacionEjecutablelPanel() {
        initComponents();
        //poner el campo de ruta como no editable
        ruta.setEditable(false);
    }

    /**
     * Devolver el valor elegido
     * @return 
     */
    public AplicacionEjecutable getSelectedValue(){
        return aej;
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ruta = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruta)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 364, Short.MAX_VALUE)
                        .addComponent(btnBuscar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ruta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap(133, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * Evento de pusacion de boton. Se muestra un filechooser y se recoge la ruta del archivo elegido.
     * Con esa ruta se genera un AplicacionEjecutable
     * @param evt 
     */
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       JFileChooser fileChooser = new JFileChooser();
        
        // Establecer filtro para mostrar solo archivos exe
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Ejecutables (*.exe)", "exe");
        fileChooser.setFileFilter(filtro);
        fileChooser.setAcceptAllFileFilterUsed(false);
        int returnValue = fileChooser.showOpenDialog(ruta);
        
        //si ha dado ok construir dato a partir de seleccion
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            String absRuta = fileChooser.getSelectedFile().getAbsolutePath();
            aej = new AplicacionEjecutable(absRuta);
            ruta.setText(absRuta);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JTextField ruta;
    // End of variables declaration//GEN-END:variables
}
